In [1]:
import numpy

ModuleNotFoundError: No module named 'numpy'

In [2]:
!pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.5 MB 9.3 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.5 MB 12.3 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.5 MB 13.2 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.5 MB 12.1 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.5 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 10.1 MB/s  0:00:01



[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: C:\Users\balaj\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
#Arrray Ceration 
data=[21,22,35]
a= np.array(data)
a

array([21, 22, 35])

In [6]:
print(type(a))
print(a.ndim)  #returns  the dimension of array
print(len(a))
print(a.size) #returns the number of elements in the array
print(a.shape)


<class 'numpy.ndarray'>
1
3
3
(3,)


In [ ]:
a=[[1,2,3],[4,5,6]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
s=np.array([[1,2,3],[4,5,6]])
s
print(s.ndim)

2


In [12]:
print(type(s))
print(len(s))
print(s.size)
print(s.shape)   #rows -->axis-0 , columns -->axis-1
print(s.itemsize)

<class 'numpy.ndarray'>
2
6
(2, 3)
8


In [28]:
#Numpy Arrays vs Lists (Fast Computataion )
import time 
#Let us create two Lists with Around 10,00,000 elements 
L1=list(range(1000000))
L2=list(range(1000000))
#print(L1+L2)   #Merging 
#we will Use our time module to get time calculation 
start= time.time()
L3=[x+y for x,y in zip(L1,L2)]
#print(L3)
end = time.time()
print(end-start)
print(f'Execution Time for Lists is {(end-start)*1000} milliseconds ')


0.074249267578125
Execution Time for Lists is 74.249267578125 milliseconds 


In [30]:
#Create  elements in Numpy array Use --- >Arange()
A1=np.arange(1000000)
A2=np.arange(1000000)
start = time.time()
A3=A1+A2
end= time.time()
print(end-start)
print(f'Execution time  for Numpy Array is {(end-start)*1000} milliseconds ')

0.002572774887084961
Execution time  for Numpy Array is 2.572774887084961 milliseconds 


In [33]:
Numpy Arrays exhibits atleast 50x better than lists. Numpy prefrom Elements wise Operation 

SyntaxError: invalid decimal literal (1066848200.py, line 1)

In [44]:
#reshape the array
a= np.arange(10).reshape(2,5)
a
b=np.arange(10).reshape(5,2)
b
c=np.arange(10).reshape(-1,2)
c
d=np.arange(10).reshape(2,-1)
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
e=np.arange(24).reshape(-1,8)
e
f=np.arange(24).reshape(3,8)
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [65]:
print(f-+2)
print(f-2)
print(f*2)
print(f/2)
a=np.array([[1,2],[3,4]])
b=np.array([[3,4],[1,2]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
#Statistical Function 
print(np.mean(e))
print(np.medain(e))
print(np.st(e))
print(np.max(e))
print(np.min(e))
print(np.minimum(a,b))


[[-2 -1  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21]]
[[-2 -1  0  1  2  3  4  5]
 [ 6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21]]
[[ 0  2  4  6  8 10 12 14]
 [16 18 20 22 24 26 28 30]
 [32 34 36 38 40 42 44 46]]
[[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10.  10.5 11.  11.5]]
[[4 6]
 [4 6]]
[[-2 -2]
 [ 2  2]]
[[3 8]
 [3 8]]
11.5


AttributeError: module 'numpy' has no attribute 'medain'

In [88]:
#Indexing and Slicing on Arrays
data=np.array([[1,4,5],[5,6,-9],[2,3,-1]])
print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0][1])
print(data[0:,0])
print(data[1:,1:])
print(data[0:2,2])
print(data[1:2,2])

[[ 1  4  5]
 [ 5  6 -9]
 [ 2  3 -1]]
[1 4 5]
[ 5  6 -9]
[ 2  3 -1]
4
[1 5 2]
[[ 6 -9]
 [ 3 -1]]
[ 5 -9]
[-9]


In [91]:
#Range of Number ---> arange(),linspace(),  -->return evenly spaced values in Intervals
a=np.linspace(1,10)   #by defaults interval=50
a
a=np.linspace(1,10,4)   #num=4 Marks 4 values to be specified 
a
a=np.linspace(1,10,4, endpoint=True,retstep=True,dtype=int)
a

(array([ 1,  4,  7, 10]), np.float64(3.0))

In [93]:
#Random Number Genertation ,Linear Algebra,stacking
a=np.random.rand()#it returns values without specifed sahpe any number 
a
b=np.random.randint(1,4)#only Integer in Given range 
b
c=np.random.randn(1,4)
c

array([[ 1.02987041, -1.11010279,  0.44131639,  0.1775809 ]])

In [101]:
#Unique values ,storing 
a=np.array([1,2,3,4,9,-1,2,3])
print(np.sort(a))
print(np.unique(a))
print(np.argmin(a))  #min index in the array
print(a>5)
print(a[a>5])

[-1  1  2  2  3  3  4  9]
[-1  1  2  3  4  9]
5
[False False False False  True False False False]
[9]


In [2]:
print(np.zeros(3))
print(np.ones(4))
print(np.eye(3))

NameError: name 'np' is not defined